import Image from "next/image";
import Link from "next/link";
import s from "./HomePage.module.css";
const Arrow = () => <span aria-hidden="true">↗</span>;
export default function HomePageClient({ faqItems }) {
  return <main id="main-content" className={s.home}>
    <section className={s.hero}>
      <div className={s.heroIntro}>
        <p className={s.eyebrow}>Pequeño / Design & build / South Africa</p>
        <h1>Bespoke luxury homes.<br /><em>Considered from the start.</em></h1>
        <div className={s.heroBottom}><p>A home shaped around your life, your landscape, and the way you want to live. Architectural thinking and precision steel construction, brought together.</p><Link className={s.button} href="/onboarding">Discuss your home <Arrow /></Link></div>
      </div>
      <figure className={s.heroImage}><Image src="/projects/Coffee_spa_1.JPG" alt="Rayton Spa & Coffee building with a glazed gable and timber terrace" fill priority sizes="100vw" /><figcaption><span>Selected built work</span><span>Rayton Spa & Coffee · Commercial project</span></figcaption></figure>
    </section>
    <section className={`${s.section} ${s.intro}`} id="homes"><p className={s.eyebrow}>01 / A more personal approach</p><div><h2>Architecture for the way<br />you <em>want to live.</em></h2><p className={s.body}>Quiet mornings. Space to gather. A view worth framing. We begin with what matters to you, then bring the site, design, budget, and construction into one considered brief.</p><p className={s.body}>Pequeño focuses on bespoke luxury home design-and-build in South Africa. We coordinate the journey with specialist professionals, including architectural partners for contract documentation.</p><Link className={s.textLink} href="/onboarding">Tell us what you have in mind <Arrow /></Link></div></section>
    <section className={s.section} id="selected-projects">
      <div className={s.sectionHeading}><div><p className={s.eyebrow}>02 / Selected experience</p><h2>Ideas, <em>built.</em></h2></div><Link className={s.textLink} href="/projects">Explore our projects <Arrow /></Link></div>
      <div className={s.projectGrid}>
        <article className={s.project}><Link href="/projects/coffee-spa" aria-label="View Coffee & Spa project" className={s.projectImage}><Image src="/projects/Coffee_spa_1.JPG" alt="Completed Rayton Spa & Coffee commercial building" fill sizes="(max-width: 700px) 100vw, 58vw" /></Link><div className={s.projectMeta}><span>Rayton, Gauteng</span><span>Commercial · 200 m²</span></div><h3><Link href="/projects/coffee-spa">Coffee & Spa</Link></h3><p>A hospitality and wellness building exploring light, volume, and the relationship between indoors and out.</p></article>
        <article className={s.project}><div className={s.projectImage}><Image src="/projects/hoedspruit_4.jpg" alt="Roof and exterior cladding detail at the Hoedspruit staff accommodation project" fill sizes="(max-width: 700px) 100vw, 40vw" /></div><div className={s.projectMeta}><span>Hoedspruit, Limpopo</span><span>Staff accommodation · 950 m²</span></div><h3>Building in the bushveld</h3><p>Residential staff accommodation demonstrating our construction experience in a demanding South African setting.</p></article>
      </div>
      <div className={s.scopeNote}><span className={s.eyebrow}>Further project experience</span><h3><Link href="/projects/somerset-west">Somerset West ↗</Link></h3><p>LSF structure supply and installation. Our involvement was limited to the structure; the completed home was outside our scope.</p></div>
    </section>
    <section className={s.services} id="our-approach"><div className={s.section}><p className={s.eyebrow}>03 / The right scope for your project</p><div className={s.serviceLead}><h2>One vision.<br /><em>A considered way to build.</em></h2><div><h3>Complete design & build</h3><p>Our primary service brings your home from the initial brief through design and construction. We establish responsibilities, professional appointments, and the delivery scope around your project before work begins.</p><Link className={s.lightLink} href="/onboarding">Start a design-and-build conversation <Arrow /></Link></div></div><div className={s.structureOptions}><div><p className={s.eyebrow}>Already have your own project team?</p><h3>Precision LSF structures</h3><p>Lightweight steel framing is also available as a separate, clearly defined package.</p></div><div><h4>Supply & installation</h4><p>We supply and install the LSF structure. Your appointed team manages the other building works.</p></div><div><h4>Supply only</h4><p>We supply the LSF structure for installation by your own team.</p></div></div><p className={s.scopeDetail}>Structure-only packages cover the LSF structure, not a weatherproof shell, fit-out, or completed home. Inclusions are agreed in your quotation.</p><Link className={s.lightLink} href="/lightweight-steel-frame-homes-south-africa">Explore lightweight steel framing <Arrow /></Link></div></section>
    <section className={s.section}><div className={s.sectionHeading}><div><p className={s.eyebrow}>04 / From first conversation to home</p><h2>Clarity at <em>every step.</em></h2></div></div><div className={s.steps}>{[
      ["01", "Define the brief", "Tell us about your land, lifestyle, priorities, and budget. Together, we establish the right scope and whether the project is a good fit."],
      ["02", "Shape the design", "Develop the home around its setting, with architectural professionals supporting design development and contract documentation."],
      ["03", "Resolve the details", "Align specifications, costs, approvals, and responsibilities before construction. Agree what is included and how the work will be delivered."],
      ["04", "Bring it to life", "Coordinate construction through the agreed scope, with a clear path to completion and handover."],
    ].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={`${s.section} ${s.budget}`}><div><p className={s.eyebrow}>05 / Begin with a realistic budget</p><h2>A beautiful home starts<br />with <em>a clear brief.</em></h2></div><div><p className={s.body}>Size is only part of the picture. Site conditions, architectural complexity, finishes, professional fees, and external works all shape the total investment.</p><p className={s.body}>Our steel-frame cost guide is a starting point for understanding the components. A structure-only price is not the budget for a completed bespoke home.</p><Link className={s.textLink} href="/articles/lightweight-steel-frame-home-cost-south-africa">Read the home cost guide <Arrow /></Link></div></section>
    <section className={`${s.section} ${s.faq}`}><div><p className={s.eyebrow}>Before we begin</p><h2>A few useful<br /><em>answers.</em></h2></div><div>{faqItems.map(item => <details key={item.question}><summary>{item.question}<span aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section>
    <section className={s.contact}><p className={s.eyebrow}>Your next chapter</p><h2>Let’s make room<br />for <em>your vision.</em></h2><p>Share your location, your ideas, and an indication of budget.<br />We’ll help you define the right next step.</p><Link className={s.button} href="/onboarding">Discuss your home <Arrow /></Link><a className={s.contactEmail} href="mailto:info@pequenohome.com">info@pequenohome.com</a></section>
  </main>;
}
